# Generated by Django 5.2 on 2025-05-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_upitransaction_remove_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='UPI', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='upi_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
